This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./rapport.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file rapport.acn....done (46 entries accepted, 0 rejected).
Sorting entries....done (276 comparisons).
Generating output file rapport.acr....done (64 lines written, 0 warnings).
Output written in rapport.acr.
Transcript written in rapport.alg.
